///////////////////////////////////////////////////////////
//  IPositionRepository.cs
//  Implementation of the Interface IPositionRepository
//  Generated by Enterprise Architect
//  Created on:      15-Apr-2017 16:36:48
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Datamodel;
namespace Repositories {
	public interface IPositionRepository   {

		/// 
		/// <param name="position"></param>
		Datamodel.Position Create(Position position);

		/// 
		/// <param name="position"></param>
		void Delete(Position position);

		/// 
		/// <param name="positionId"></param>
		Datamodel.Position GetPosition(int positionId);

        /// <summary>
        /// TODO: List
        /// </summary>
        /// <param name="numSteps"></param>
        /// <param name="startPositionId"></param>
        IEnumerable<Position> GetPredeccessors(int numSteps, int startPositionId);

        /// <summary>
        /// Todo: List
        /// </summary>
        /// <param name="numSteps"></param>
        /// <param name="startPositionId"></param>
        IEnumerable<Position> GetSuccessors(int numSteps, int startPositionId);

		/// 
		/// <param name="position"></param>
		Datamodel.Position Update(Position position);
	}//end IPositionRepository

}//end namespace Repositories