///////////////////////////////////////////////////////////
//  IRuleRepository.cs
//  Implementation of the Interface IRuleRepository
//  Generated by Enterprise Architect
//  Created on:      15-Apr-2017 16:36:48
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Datamodel;
namespace Repositories {
	public interface IRuleRepository  {

		/// 
		/// <param name="rule"></param>
		Datamodel.Rule Create(Rule rule);

		/// 
		/// <param name="rule"></param>
		void Delete(Rule rule);

		/// <summary>
		/// TODO:List
		/// </summary>
		List<Rule> GetAllRules();

		/// <summary>
		/// Todo: List
		/// </summary>
		List<Rule> GetDynamicRules();

		/// 
		/// <param name="ruleId"></param>
		Datamodel.Rule GetRule(int ruleId);

		/// <summary>
		/// Todo: List
		/// </summary>
		List<Rule> GetStaticRules();

		/// 
		/// <param name="rule"></param>
		Datamodel.Rule Update(Rule rule);
	}//end IRuleRepository

}//end namespace Repositories