///////////////////////////////////////////////////////////
//  AgentSimConfiguration.cs
//  Implementation of the Class AgentSimConfiguration
//  Generated by Enterprise Architect
//  Created on:      18-Apr-2017 20:10:41
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Datamodel {
	public class AgentSimConfiguration {

		public AgentSimConfiguration(){

		}

		~AgentSimConfiguration(){

		}

		public int Acceleration{
			get;
			set;
		}

		public int AccelerationSpread{
			get;
			set;
		}

		public AgentType AgentType{
			get;
			set;
		}

		public int Deceleration{
			get;
			set;
		}

		public int DecelerationSpread{
			get;
			set;
		}

		public int SpawnPropability{
			get;
			set;
		}

		public int Velocity{
			get;
			set;
		}

		public int VelocitySpread{
			get;
			set;
		}

        /// <summary>
        /// Mean value of vehicle lengths for this agent configuration in meters
        /// </summary>
        public int VehicleLength { get; set; }

        /// <summary>
        /// Spread of values of vehicle lengths for this agent configuration in meters
        /// </summary>
        public int VehicleLengthSpread { get; set; }

	}//end AgentSimConfiguration

}//end namespace Datamodel