///////////////////////////////////////////////////////////
//  AgentType.cs
//  Implementation of the Enumeration AgentType
//  Generated by Enterprise Architect
//  Created on:      15-Apr-2017 16:36:47
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Datamodel {

    /// <summary>
    /// The available agent types of the simulation
    /// </summary>
	public enum AgentType : int {
        /// <summary>
        /// Car type one
        /// </summary>
        Car01 = 1,

        /// <summary>
        /// Car type two
        /// </summary>
        Car02 = 2,

        /// <summary>
        /// Truck type one
        /// </summary>
        Lkw01 = 3,

        /// <summary>
        /// Truck type two
        /// </summary>
        Lkw02 = 4
	}//end AgentType

}//end namespace Datamodel