///////////////////////////////////////////////////////////
//  AgentSimConfiguration.cs
//  Implementation of the Class AgentSimConfiguration
//  Generated by Enterprise Architect
//  Created on:      18-Apr-2017 20:10:41
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Datamodel {

    /// <summary>
    /// Agent sim configuration objects contain spawn informations for different agent types
    /// </summary>
	public class AgentSimConfiguration : BaseModel {

        /// <summary>
        /// Mean acceleration for the current agent type in m/s^2
        /// </summary>
		public int Acceleration{
			get;
			set;
		}

        /// <summary>
        /// Spread (+-) in m/s^2 for the acceleration
        /// </summary>
		public int AccelerationSpread{
			get;
			set;
		}

        /// <summary>
        /// Type for which this configuration object is for
        /// </summary>
		public AgentType AgentType{
			get;
			set;
		}

        /// <summary>
        /// Mean decelaration for the current agent type in m/s^2
        /// </summary>
		public int Deceleration{
			get;
			set;
		}

        /// <summary>
        /// Spread (+-) for the deceleration in m/s^2
        /// </summary>
		public int DecelerationSpread{
			get;
			set;
		}

        /// <summary>
        /// Probability in percent, that the agent type will spawn on each spawner tick.
        /// </summary>
		public int SpawnPropability{
			get;
			set;
		}

        /// <summary>
        /// Mean max velocity for the current agent type in m/s
        /// </summary>
		public int Velocity{
			get;
			set;
		}

        /// <summary>
        /// Spread (+-) of the max velocity in m/s
        /// </summary>
		public int VelocitySpread{
			get;
			set;
		}

        /// <summary>
        /// Mean value of vehicle lengths for this agent configuration in meters
        /// </summary>
        public int VehicleLength { get; set; }

        /// <summary>
        /// Spread of values of vehicle lengths for this agent configuration in meters
        /// </summary>
        public int VehicleLengthSpread { get; set; }

	}//end AgentSimConfiguration

}//end namespace Datamodel