///////////////////////////////////////////////////////////
//  Crossway.cs
//  Implementation of the Crossway (Ampellichter, die von 
//  einer Ampel verwaltet werden
//  Generated by Enterprise Architect
//  Created on:      01-Jun-2017 17:37:23
//  Original author: maxi
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Datamodel
{
    /// <summary>
    /// The crossway is used as a group for the crossway directions for the traffic light control
    /// </summary>
    public class Crossway : BaseModel
    {
        /// <summary>
        /// Default constructor of the crossway initializes the greenphase list with an empty list.
        /// </summary>
        public Crossway()
        {
            greenphase = new List<CrosswayDirection>();
        }
        
        /// <summary>
        /// The greenphase collection for the current crossway
        /// </summary>
        public List<CrosswayDirection> greenphase;

    } //end Crossway

}//end namespace Datamodel