///////////////////////////////////////////////////////////
//  CrosswayDirection.cs
//  Implementation of the CrosswayDirection
//  (Ampellichter, die gleichzeitig grün sein können)
//  Generated by Enterprise Architect
//  Created on:      01-Jun-2017 17:04:23
//  Original author: maxi
///////////////////////////////////////////////////////////
using System.Collections.Generic;

namespace Datamodel
{
    public class CrosswayDirection
    {
        public int hightime;
        public List<int> concurrentGreen;
    }
}
