///////////////////////////////////////////////////////////
//  CrosswayDirection.cs
//  Implementation of the CrosswayDirection
//  (Ampellichter, die gleichzeitig grün sein können)
//  Generated by Enterprise Architect
//  Created on:      01-Jun-2017 17:04:23
//  Original author: maxi
///////////////////////////////////////////////////////////
using System.Collections.Generic;

namespace Datamodel
{
    /// <summary>
    /// Side of a crossway for traffic light control
    /// </summary>
    public class CrosswayDirection
    {
        /// <summary>
        /// Time the traffic light is green
        /// </summary>
        public int hightime;

        /// <summary>
        /// List of other crossway sites that are green at the same time
        /// </summary>
        public List<int> concurrentGreen;
    }
}
