///////////////////////////////////////////////////////////
//  Map.cs
//  Implementation of the Class Map
//  Generated by Enterprise Architect
//  Created on:      15-Apr-2017 16:36:48
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Datamodel {
    /// <summary>
    /// Metadata for the map that will be rendered in the gui
    /// </summary>
	public class Map {
        
        /// <summary>
        /// Background image of the map base64 encoded
        /// </summary>
		public char[] BackgroundImageBase64{
			get;
			set;
		}

        /// <summary>
        /// Height of the map in pixels
        /// </summary>
		public int Height{
			get;
			set;
		}

        /// <summary>
        /// Width of the map in pixels
        /// </summary>
		public int Width{
			get;
			set;
		}

	}//end Map

}//end namespace Datamodel