///////////////////////////////////////////////////////////
//  RuleType.cs
//  Implementation of the Enumeration RuleType
//  Generated by Enterprise Architect
//  Created on:      15-Apr-2017 16:36:48
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Datamodel {
	public enum RuleType : int {

	}//end RuleType

}//end namespace Datamodel