///////////////////////////////////////////////////////////
//  RuleType.cs
//  Implementation of the Enumeration RuleType
//  Generated by Enterprise Architect
//  Created on:      15-Apr-2017 16:36:48
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Datamodel {
	public enum RuleType : int {
        Stopp = 1,
        Vorrang = 2,
        Geschwindigkeit = 3,
        Ampel = 4
}//end RuleType

}//end namespace Datamodel