///////////////////////////////////////////////////////////
//  Map.cs
//  Implementation of the Class Map
//  Generated by Enterprise Architect
//  Created on:      15-Apr-2017 16:36:48
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Datamodel {
	public class Map {

		public Map(){

		}

		~Map(){

		}

		public char BackgroundImageBase64{
			get;
			set;
		}

		public int Height{
			get;
			set;
		}

		public int Width{
			get;
			set;
		}

	}//end Map

}//end namespace Datamodel