///////////////////////////////////////////////////////////
//  Agent.cs
//  Implementation of the Class Agent
//  Generated by Enterprise Architect
//  Created on:      15-Apr-2017 16:36:47
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Datamodel {
	public class Agent {

		public Agent(){

		}

		~Agent(){

		}

		public int CurrentVelocity{
			get;
			set;
		}

		public int Id{
			get;
			set;
		}

		public int EdgeId { get; set; }

        public int RunLength { get; set; }

		public AgentType Type{
			get;
			set;
		}

		public int Acceleration{
			get;
			set;
		}

		public int Deceleration{
			get;
			set;
		}

		public int MaxVelocity{
			get;
			set;
		}

        /// <summary>
        /// Vehicle length in meters
        /// </summary>
        public int VehicleLength { get; set; }

	}//end Agent

}//end namespace Datamodel