///////////////////////////////////////////////////////////
//  AgentType.cs
//  Implementation of the Enumeration AgentType
//  Generated by Enterprise Architect
//  Created on:      15-Apr-2017 16:36:47
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Datamodel {
	public enum AgentType : int {

	}//end AgentType

}//end namespace Datamodel