///////////////////////////////////////////////////////////
//  IAgentSim.cs
//  Implementation of the Interface IAgentSim
//  Generated by Enterprise Architect
//  Created on:      18-Apr-2017 20:06:25
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Datamodel;
namespace AgentSim {
	public interface IAgentSim  {

		/// 
		/// <param name="agent"></param>
		void SpawnAgent(Agent agent);

		void Start();

		void Stop();
	}//end IAgentSim

}//end namespace AgentSim