///////////////////////////////////////////////////////////
//  AgentSimConfigurationRepositoryFactory.cs
//  Implementation of the Class AgentSimConfigurationRepositoryFactory
//  Generated by Enterprise Architect
//  Created on:      18-Apr-2017 20:10:05
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Repositories;
namespace Repositories {
    /// <summary>
    /// Factory class to decouple components.
    /// </summary>
    public abstract class AgentSimConfigurationRepositoryFactory {
        /// <summary>
        /// Factory to return new service. 
        /// </summary>
        /// <returns>AgentSimConfigurationService</returns>
        public static IAgentSimConfigurationRepository CreateRepository(){

            return new DataBridge.Services.AgentSimConfigurationService();
		}

	}//end AgentSimConfigurationRepositoryFactory

}//end namespace Repositories