///////////////////////////////////////////////////////////
//  AgentRepositoryFactory.cs
//  Implementation of the Class AgentRepositoryFactory
//  Generated by Enterprise Architect
//  Created on:      15-Apr-2017 16:36:47
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Repositories;
namespace Repositories {
	public abstract class AgentRepositoryFactory {

		public static IAgentRepository CreateRepository(){

            return new DataBridge.Services.MockedAgentService();
		}

	}//end AgentRepositoryFactory

}//end namespace Repositories