///////////////////////////////////////////////////////////
//  AgentRepositoryFactory.cs
//  Implementation of the Class AgentRepositoryFactory
//  Generated by Enterprise Architect
//  Created on:      15-Apr-2017 16:36:47
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Repositories;
using DataBridge;
using DataBridge.Services;

namespace Repositories {
    /// <summary>
    /// Factory class to decouple components.
    /// </summary>
	public abstract class AgentRepositoryFactory {

        /// <summary>
        /// Factory to return new service. 
        /// </summary>
        /// <returns>AgentService</returns>
		public static IAgentRepository CreateRepository(){
            return new AgentService();
		}

	}//end AgentRepositoryFactory

}//end namespace Repositories