///////////////////////////////////////////////////////////
//  IAgentSimConfigurationRepository.cs
//  Implementation of the Interface IAgentSimConfigurationRepository
//  Generated by Enterprise Architect
//  Created on:      18-Apr-2017 20:10:14
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


using Datamodel;
namespace Repositories {
    /// <summary>
    /// IAgentSimConfigurationRepository
    /// </summary>
	public interface IAgentSimConfigurationRepository  {

        /// <summary>
        /// Get all AgentSimConfigurations.
        /// </summary>
        /// <returns>List of AgentSimConfigurations or null</returns>
		IEnumerable<AgentSimConfiguration> GetAll();
	}//end IAgentSimConfigurationRepository

}//end namespace Repositories