///////////////////////////////////////////////////////////
//  IAgentSimConfigurationRepository.cs
//  Implementation of the Interface IAgentSimConfigurationRepository
//  Generated by Enterprise Architect
//  Created on:      18-Apr-2017 20:10:14
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Repositories {
	public interface IAgentSimConfigurationRepository  {

		IEnumerable<AgentSimConfiguration> GetAll();
	}//end IAgentSimConfigurationRepository

}//end namespace Repositories