///////////////////////////////////////////////////////////
//  ICrosswayRepository.cs
//  Implementation of the Interface ICrosswayRepository
//  Generated by Enterprise Architect
//  Created on:      18-Apr-2017 20:10:14
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Datamodel;

namespace Repositories
{
    public interface ICrosswayRepository
    {
        Datamodel.Crossway Create(Crossway crossway);
        void Delete(Crossway crossway);
        Crossway GetCrossway(int crosswayId);
        Crossway Update(Crossway crossway);

        IEnumerable<Crossway> GetAll();
    }
}

