///////////////////////////////////////////////////////////
//  IEdgeRepository.cs
//  Implementation of the Interface IEdgeRepository
//  Generated by Enterprise Architect
//  Created on:      18-Apr-2017 20:10:14
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

using Datamodel;

namespace Repositories
{
    public interface IEdgeRepository
    {
        Datamodel.Edge Create(Edge edge);
        void Delete(Edge edge);
        Edge GetEdge(int edgeId);
        Edge Update(Edge edge);

        IEnumerable<Edge> GetAll();
    }
}
