///////////////////////////////////////////////////////////
//  IMapRepository.cs
//  Implementation of the Interface IMapRepository
//  Generated by Enterprise Architect
//  Created on:      15-Apr-2017 16:36:48
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Repositories {
    /// <summary>
    /// IMapRepository
    /// </summary>
	public interface IMapRepository      {

        /// <summary>
        /// Get the map.
        /// </summary>
        /// <returns>Map or null</returns>
		Datamodel.Map GetMap();
	}//end IMapRepository

}//end namespace Repositories