///////////////////////////////////////////////////////////
//  MapRepositoryFactory.cs
//  Implementation of the Class MapRepositoryFactory
//  Generated by Enterprise Architect
//  Created on:      15-Apr-2017 16:36:48
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Repositories;
using DataBridge.Services;

namespace Repositories {
    /// <summary>
    /// Factory class to decouple components.
    /// </summary>
    public abstract class MapRepositoryFactory {
        /// <summary>
        /// Factory to return new service. 
        /// </summary>
        /// <returns>MockedMapService</returns>
        public static IMapRepository CreateRepository(){

			return new MockedMapService();
		}

	}//end MapRepositoryFactory

}//end namespace Repositories