///////////////////////////////////////////////////////////
//  PositionRepositoryFactory.cs
//  Implementation of the Class PositionRepositoryFactory
//  Generated by Enterprise Architect
//  Created on:      15-Apr-2017 16:36:48
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Repositories;
namespace Repositories {
	public abstract class PositionRepositoryFactory {

		public static IPositionRepository CreateRepository(){

			return null;
		}

	}//end PositionRepositoryFactory

}//end namespace Repositories