///////////////////////////////////////////////////////////
//  ISimulation.cs
//  Implementation of the Interface ISimulation
//  Generated by Enterprise Architect
//  Created on:      18-Apr-2017 20:03:28
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Simulation {

	/// <summary>
	/// Simulation runs the agent sim and stops it if requested.
	/// </summary>
	public interface ISimulation  {
        /// <summary>
        /// Starts the simulation thread.
        /// </summary>
		void Start();

        /// <summary>
        /// Stops the simulation thread.
        /// </summary>
		void Stop();
	}//end ISimulation

}//end namespace Simulation