///////////////////////////////////////////////////////////
//  ISimulation.cs
//  Implementation of the Interface ISimulation
//  Generated by Enterprise Architect
//  Created on:      18-Apr-2017 20:03:28
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Simulation {
	public interface ISimulation  {

		void LoadConfiguration();

		void Start();

		void Stop();
	}//end ISimulation

}//end namespace Simulation