///////////////////////////////////////////////////////////
//  IWatchdog.cs
//  Implementation of the Interface IWatchdog
//  Generated by Enterprise Architect
//  Created on:      18-Apr-2017 20:03:28
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Simulation {
    /// <summary>
    /// Interface for the Watchdog that is responsible for watching over all sub processes of the traffic simulation
    /// </summary>
	public interface IWatchdog  {
        /// <summary>
        /// Starts the watchdog thread
        /// </summary>
		void Start();

        /// <summary>
        /// Stops the watchdog thread
        /// </summary>
		void Stop();

        /// <summary>
        /// Start the watching over all sub processes of the traffic simulation
        /// </summary>
		void Watch();
	}//end IWatchdog

}//end namespace Simulation