///////////////////////////////////////////////////////////
//  IWatchdog.cs
//  Implementation of the Interface IWatchdog
//  Generated by Enterprise Architect
//  Created on:      18-Apr-2017 20:03:28
//  Original author: David
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Simulation {
	public interface IWatchdog  {

		void Start();

		void Stop();

		void Watch();
	}//end IWatchdog

}//end namespace Simulation